FROM python:3.9-slim

WORKDIR /app

COPY beauty_back/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY beauty_back/ .

CMD ["python", "manage.py", "runserver", "127.0.0.1:8000"]