export const ADD_TO_CHART = 'ADD_TO_CHART';
export const  REMOVE_FROM_CHART = ' REMOVE_FROM_CHART';
export const  DELETE_FROM_CHART = ' DELETE_FROM_CHART';

export default {
  ADD_TO_CHART,
  REMOVE_FROM_CHART,
  DELETE_FROM_CHART
};