# Generated by Django 4.1.1 on 2025-02-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('tel', models.CharField(blank=True, max_length=45, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BigCategories',
            fields=[
                ('BigCategory_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'big_cats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('Chart_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('auth_user', models.ForeignKey(db_column='auth_user', on_delete=django.db.models.deletion.DO_NOTHING, to='online_store.authuser')),
            ],
            options={
                'db_table': 'chart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmallCategories',
            fields=[
                ('SmallCategory_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(db_column='parent', on_delete=django.db.models.deletion.DO_NOTHING, to='online_store.bigcategories')),
            ],
            options={
                'db_table': 'small_cats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('number_of_order', models.CharField(max_length=45)),
                ('date_of_delivery', models.DateField()),
                ('date_made', models.DateField()),
                ('delivery_mode', models.CharField(max_length=45)),
                ('auth_user', models.ForeignKey(db_column='auth_user', on_delete=django.db.models.deletion.DO_NOTHING, to='online_store.authuser')),
                ('chart_id', models.ForeignKey(db_column='chart_id', on_delete=django.db.models.deletion.DO_NOTHING, to='online_store.chart')),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('Item_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=45, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.DO_NOTHING, to='online_store.smallcategories')),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='online_store.items'),
        ),
    ]
